services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-8.5}
    working_dir: /php
    user: ${UID:-root}:${GID:-root}
    tty: true
    environment:
      - XDG_CACHE_HOME=/tmp/cache
    volumes:
      - .:/php
      - /etc/machine-id:/etc/machine-id:ro
    extra_hosts:
        - host.docker.internal:host-gateway
